version: '3.3'

services:
  api-backend:
    build:
      context: ./api-backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3336:3336"
    networks:
      my-network:
        aliases:
          - api
  
  transversal-backend:
    build:
      context: ./transversal-backend
      dockerfile: Dockerfile
    restart: always
    networks:
      my-network:
        aliases:
          - transversal

  medical-backend:
    build:
      context: ./medical-backend
      dockerfile: Dockerfile
    restart: always
    networks:
      my-network:
        aliases:
          - medical

networks:
  my-network:
    driver: bridge