version: '3.3'

services:
  api-service:
    build:
      context: ./api-backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3336:3336"
    networks:
      my-network:
        aliases:
          - api
  
  transversal-service:
    build:
      context: ./transversal-backend
      dockerfile: Dockerfile
    restart: always
    networks:
      my-network:
        aliases:
          - transversal

  medical-service:
    build:
      context: ./medical-backend
      dockerfile: Dockerfile
    restart: always
    networks:
      my-network:
        aliases:
          - medical

  ai-service:
    build:
      context: ./ai-api
      dockerfile: Dockerfile
    restart: always
    networks:
      my-network:
        aliases:
          - ai


networks:
  my-network:
    driver: bridge