

### request with adonis
POST http://127.0.0.1:3333/api/auth/register
Content-Type: application/json

{
  "email": "2example23@mail.com",
  "username": "2testUsername",
  "password": "123456789"
}
### login with adonis

POST http://127.0.0.1:3333/api/auth/login
Content-Type: application/json

{
  "email": "2example2@mail.com",
  "password": "123456789"
}
### access to protected route with bearer token
GET http://127.0.0.1:3333/
Authorization: Bearer MQ.86XA3laBLbtw6X4yofHSoIa7Xhin9Bvr2TZ-tfiteyh2WeT36_VIll4hqhu_

### try to access to protected  route without token 
GET http://127.0.0.1:3333/
Content-Type: application/json

{
}